dist: xenial
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - rustc --version | grep nightly -q && cargo bench || true
